import { useState } from 'react'
import { motion } from 'framer-motion'
import { Download, Loader2 } from 'lucide-react'
import { useInspection } from '../store/inspectionStore'
import { jsPDF } from 'jspdf'
import type { InspectionResult, BatchStats } from '../types'

/* ── Layout constants (A4 mm) ── */
const PAGE_W = 210
const PAGE_H = 297
const MARGIN = 18
const INNER = PAGE_W - MARGIN * 2

const C_TEXT: [number, number, number] = [30, 30, 36]
const C_MUTED: [number, number, number] = [110, 110, 120]
const C_BORDER: [number, number, number] = [220, 220, 228]
const C_FILL: [number, number, number] = [245, 246, 248]
const C_ACCENT: [number, number, number] = [44, 160, 240]
const C_OK: [number, number, number] = [40, 170, 90]
const C_WARN: [number, number, number] = [230, 140, 0]
const C_REJECT: [number, number, number] = [220, 40, 40]

function statusColor(s: string): [number, number, number] {
  return s === 'pass' ? C_OK : s === 'rework' ? C_WARN : C_REJECT
}

/* ── Helper: object-url to base64 data-URI ── */
function urlToDataUri(url: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest()
    xhr.onload = () => {
      const reader = new FileReader()
      reader.onloadend = () => resolve(reader.result as string)
      reader.onerror = () => reject(new Error('Read failed'))
      reader.readAsDataURL(xhr.response)
    }
    xhr.onerror = () => reject(new Error('Fetch failed'))
    xhr.responseType = 'blob'
    xhr.open('GET', url)
    xhr.send()
  })
}

function stripPrefix(dataUri: string): { mime: 'JPEG' | 'PNG'; base64: string } {
  const match = dataUri.match(/^data:(image\/(?:png|jpeg|webp));base64,(.+)$/)
  if (match) {
    const m = match[1] === 'image/png' ? 'PNG' : 'JPEG'
    return { mime: m, base64: match[2] }
  }
  return { mime: 'JPEG', base64: dataUri.split(',')[1] ?? '' }
}

/* ── PDF generation ── */
async function generateDetailedPDF(results: InspectionResult[], batchStats: BatchStats) {
  const imageMap = new Map<string, string>()
  await Promise.all(
    results.map(async (r) => {
      try {
        const dataUri = await urlToDataUri(r.imageUrl)
        imageMap.set(r.id, dataUri)
      } catch {
        imageMap.set(r.id, '')
      }
    })
  )

  const pdf = new jsPDF('p', 'mm', 'a4')
  let y = MARGIN

  /* ========== COVER PAGE ========== */
  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(26)
  pdf.setTextColor(...C_TEXT)
  pdf.text('Garment Quality Inspection Report', PAGE_W / 2, y + 20, { align: 'center' })

  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(11)
  pdf.setTextColor(...C_MUTED)
  const now = new Date()
  pdf.text(`Generated on ${now.toLocaleString()}`, PAGE_W / 2, y + 30, { align: 'center' })

  y += 55

  pdf.setFillColor(...C_FILL)
  pdf.roundedRect(MARGIN, y, INNER, 85, 3, 3, 'F')
  pdf.setDrawColor(...C_BORDER)
  pdf.roundedRect(MARGIN, y, INNER, 85, 3, 3, 'S')

  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(14)
  pdf.setTextColor(...C_TEXT)
  pdf.text('Batch Summary', MARGIN + 8, y + 14)

  const drawSummaryKV = (label: string, value: string, color: [number, number, number], x: number, rowY: number) => {
    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(8)
    pdf.setTextColor(...C_MUTED)
    pdf.text(label, x, rowY)
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(11)
    pdf.setTextColor(...color)
    pdf.text(value, x, rowY + 5)
  }

  let row = y + 22
  drawSummaryKV('Total Inspected', String(batchStats.total), C_TEXT, MARGIN + 8, row)
  drawSummaryKV('Passed', String(batchStats.passed), C_OK, MARGIN + 60, row)
  drawSummaryKV('Rework', String(batchStats.rework), C_WARN, MARGIN + 112, row)
  drawSummaryKV('Rejected', String(batchStats.rejected), C_REJECT, MARGIN + 164, row)

  row += 18
  drawSummaryKV('Pass Rate', `${batchStats.passRate}%`, C_OK, MARGIN + 8, row)
  drawSummaryKV('Total Defects', String(batchStats.totalDefects), C_REJECT, MARGIN + 60, row)
  drawSummaryKV('Est. Rework Cost', `Rs.${batchStats.estimatedBatchCost.min} - ${batchStats.estimatedBatchCost.max}`, C_TEXT, MARGIN + 112, row)

  /* Footer */
  pdf.setFont('helvetica', 'italic')
  pdf.setFontSize(9)
  pdf.setTextColor(...C_MUTED)
  pdf.text('Generated by FabricScan AI - Confidential Quality Control Document', PAGE_W / 2, PAGE_H - MARGIN, { align: 'center' })

  /* ========== PER-ITEM PAGES ========== */
  for (let i = 0; i < results.length; i++) {
    pdf.addPage()
    let itemY = MARGIN
    const r = results[i]
    const imgDataUri = imageMap.get(r.id) || ''

    pdf.setFillColor(...C_FILL)
    pdf.rect(MARGIN, itemY, INNER, 18, 'F')
    pdf.setDrawColor(...C_BORDER)
    pdf.line(MARGIN, itemY, PAGE_W - MARGIN, itemY)
    pdf.line(MARGIN, itemY + 18, PAGE_W - MARGIN, itemY + 18)

    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(12)
    pdf.setTextColor(...C_TEXT)
    pdf.text(`${i + 1}. ${r.imageName}`, MARGIN + 6, itemY + 11)

    const badgeColor = statusColor(r.overallStatus)
    pdf.setFillColor(...badgeColor)
    pdf.setTextColor(255, 255, 255)
    const statusLabel = r.overallStatus.toUpperCase()
    const badgeW = pdf.getTextWidth(statusLabel) + 12
    pdf.roundedRect(PAGE_W - MARGIN - badgeW, itemY + 3.5, badgeW, 11, 2, 2, 'F')
    pdf.text(statusLabel, PAGE_W - MARGIN - badgeW / 2, itemY + 10, { align: 'center' })

    itemY += 24

    /* Image */
    if (imgDataUri) {
      try {
        const { mime, base64 } = stripPrefix(imgDataUri)
        const maxW = INNER
        const maxH = 90
        pdf.addImage(base64, mime, MARGIN, itemY, maxW, maxH)
        itemY += maxH + 12
      } catch {
        pdf.setFont('helvetica', 'italic')
        pdf.setFontSize(10)
        pdf.setTextColor(...C_MUTED)
        pdf.text('[Image could not be embedded]', MARGIN, itemY + 6)
        itemY += 12
      }
    }

    /* Defects */
    if (r.defects.length === 0) {
      pdf.setFont('helvetica', 'bold')
      pdf.setFontSize(12)
      pdf.setTextColor(...C_OK)
      pdf.text('No defects detected - this item passes quality inspection.', MARGIN, itemY + 6)
      itemY += 16
    } else {
      for (let di = 0; di < r.defects.length; di++) {
        const d = r.defects[di]
        const tx = MARGIN + 8
        const tw = INNER - 16
        const LH = 3.65

        /* Page break check */
        if (itemY + 60 > PAGE_H - MARGIN - 10) {
          pdf.addPage()
          itemY = MARGIN
        }

        /* Separator between defects */
        if (di > 0) {
          pdf.setDrawColor(...C_BORDER)
          pdf.setLineWidth(0.3)
          pdf.line(tx, itemY, PAGE_W - MARGIN - 8, itemY)
          itemY += 5
        }

        /* Header: accent bar + label + severity badge */
        pdf.setDrawColor(...C_ACCENT)
        pdf.setLineWidth(1.2)
        pdf.line(MARGIN + 4, itemY, MARGIN + 4, itemY + 10)

        pdf.setFont('helvetica', 'bold')
        pdf.setFontSize(11)
        pdf.setTextColor(...C_TEXT)
        pdf.text(`Defect #${di + 1}: ${d.label}`, MARGIN + 12, itemY + 7)

        const sevColor = statusColor(d.severity)
        pdf.setFillColor(...sevColor)
        pdf.setTextColor(255, 255, 255)
        const sevLabel = d.severity.toUpperCase()
        const sevW = pdf.getTextWidth(sevLabel) + 10
        pdf.roundedRect(PAGE_W - MARGIN - sevW, itemY, sevW, 10, 1.5, 1.5, 'F')
        pdf.text(sevLabel, PAGE_W - MARGIN - sevW / 2, itemY + 6, { align: 'center' })

        itemY += 16

        const addBlock = (label: string, text: string, color: [number, number, number]) => {
          pdf.setFont('helvetica', 'bold')
          pdf.setFontSize(8.5)
          pdf.setTextColor(...color)
          pdf.text(label, tx, itemY)
          itemY += 4

          pdf.setFont('helvetica', 'normal')
          pdf.setFontSize(9)
          pdf.setTextColor(...C_TEXT)
          const lines = pdf.splitTextToSize(text, tw)
          pdf.text(lines, tx, itemY)
          itemY += lines.length * LH + 3
        }

        addBlock('DESCRIPTION', d.description, C_MUTED)
        if (d.location) addBlock('LOCATION', d.location, C_ACCENT)
        if (d.why) addBlock('WHY THIS IS A DEFECT', d.why, C_ACCENT)
        if (d.impact) addBlock('IMPACT IF NOT FIXED', d.impact, C_REJECT)
        if (d.reworkInstructions) addBlock('HOW TO FIX', d.reworkInstructions, C_OK)

        /* Metrics row */
        const metricsY = itemY
        pdf.setDrawColor(...C_BORDER)
        pdf.setLineWidth(0.3)
        pdf.line(tx, metricsY, PAGE_W - MARGIN - 8, metricsY)
        itemY += 5

        pdf.setFont('helvetica', 'bold')
        pdf.setFontSize(8)
        pdf.setTextColor(...C_MUTED)
        pdf.text('Confidence', tx, itemY)
        pdf.text('Severity', tx + 60, itemY)
        pdf.text('Est. Cost', tx + 110, itemY)
        pdf.text('Action', tx + 155, itemY)
        itemY += 4

        pdf.setFont('helvetica', 'bold')
        pdf.setFontSize(9)
        pdf.setTextColor(...C_TEXT)
        pdf.text(`${Math.round(d.confidence * 100)}%`, tx, itemY)
        pdf.text(d.severity.toUpperCase(), tx + 60, itemY)
        pdf.setTextColor(...C_WARN)
        pdf.text(`₹${d.estimatedCostINR.min}–${d.estimatedCostINR.max}`, tx + 110, itemY)
        const actC = d.recommendation === 'pass' ? C_OK : d.recommendation === 'rework' ? C_WARN : C_REJECT
        pdf.setTextColor(...actC)
        pdf.text(d.recommendation.toUpperCase(), tx + 155, itemY)
        itemY += 14
      }
    }

    /* Footer on item page */
    pdf.setFont('helvetica', 'italic')
    pdf.setFontSize(9)
    pdf.setTextColor(...C_MUTED)
    pdf.text('Generated by FabricScan AI - Confidential Quality Control Document', PAGE_W / 2, PAGE_H - MARGIN, { align: 'center' })
  }

  pdf.save(`inspection_report_${Date.now()}.pdf`)
}

/* ── React Component ── */
export function ExportReport() {
  const { state, batchStats } = useInspection()
  const [isExporting, setIsExporting] = useState(false)

  if (state.results.length === 0) return null

  const handleExport = async () => {
    setIsExporting(true)
    try {
      await generateDetailedPDF(state.results, batchStats)
    } catch (err) {
      console.error('PDF export failed:', err)
      alert('Failed to generate PDF. Check console for details.')
    } finally {
      setIsExporting(false)
    }
  }

  return (
    <div style={{ display: 'flex', justifyContent: 'center', marginTop: 40, paddingBottom: 60 }}>
      <motion.button
        className="btn btn-primary btn-lg"
        onClick={handleExport}
        disabled={isExporting}
        whileHover={{ scale: 1.015 }}
        whileTap={{ scale: 0.985 }}
        style={{ width: '100%', maxWidth: 300, justifyContent: 'center' }}
      >
        {isExporting ? <Loader2 size={18} className="animate-spin" /> : <Download size={18} />}
        {isExporting ? ' Generating PDF...' : ' Export PDF Report'}
      </motion.button>
    </div>
  )
}
